#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Miyazawa kaoeu
#SPDX -Licensa -Identifier:BSD -3 -Clause
import sys
ansa = ansb = ansc = ansd = 0.0
for line in sys.stdin:

       ansa += float(line)
       ansb -= float(line)
       ansc *= float(line)
       ansd /= float(line)
print(ansa) 
           
