#SPDX-FileCopyrightText: 2022 Miyazawa kaoeu
##SPDX -Licensa -Identifier:BSD -3 -Clause
name: test        
on: push          
jobs:             
 test:           
  runs-on: ubuntu-latest   
  strategy:
   matrix:
     python-version: ["3.7", "3.8", "3.9", "3.10"]
  steps:                   
  - uses: actions/checkout@v3  
    #- name: All test1             
    #run: bash -xv ./test.bash
  - name: All test2
    run: bash -xv ./test_plus.bash
